django/conf/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('_nested_admin/', include('nested_admin.urls')),

    path('admin/', admin.site.urls),
    path("", include("web.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/web/urls.py
from django.urls import include, path

from web.views import HomeView, TestView

app_name = "web"
urlpatterns = [
    path("clients/", include("web.clients.urls", namespace="clients")),
    path("transfers/", include("web.transfers.urls", namespace="transfers")),
    path("referrals/", include("web.referrals.urls", namespace="referrals")),
    path("procedures/", include("web.procedures.urls", namespace="procedures")),
    path("statistics/", include("web.statistics.urls", namespace="statistics")),
    path("home/", HomeView.as_view(), name="home"),
    path("test/", TestView.as_view(), name="test"),
    path("", include("web.auth.urls", namespace="auth")),
]

django/templates/parts/alerts.html
{% load static %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} border-0 d-flex align-items-center" role="alert">
            <div class="bg-{{ message.tags }} me-3 icon-item">
                <span class="fas fa-check-circle text-white fs-6"></span>
            </div>
            <p class="mb-0 flex-1">{{ message }}</p>
            <button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

django/templates/parts/footer.html
{% load static %}
<footer class="footer">
    <div class="row g-0 justify-content-between fs-10 mt-4 mb-3">
        <div class="col-12 col-sm-auto text-center">
            <p class="mb-0 text-600">Bizning xizmatdan foydalanganingiz uchun raxmat.<span
                    class="d-none d-sm-inline-block">| </span><br class="d-sm-none"/> 2024 &copy; <a
                    href="https://t.me/Zuxriddin099">Medical-CRM</a></p>
        </div>
        <div class="col-12 col-sm-auto text-center">
            <p class="mb-0 text-600">v1.0.0</p>
        </div>
    </div>
</footer>

django/templates/parts/head.html
{% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- ===============================================--><!--    Favicons--><!-- ===============================================-->
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/img/favicons/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/favicons/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/img/favicons/favicon-16x16.png' %}">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicons/favicon.ico' %}">
<link rel="manifest" href="{% static 'assets/img/favicons/manifest.json' %}">
<meta name="msapplication-TileImage" content="{% static 'assets/img/favicons/mstile-150x150.png' %}">
<meta name="theme-color" content="#ffffff">
<script src="{% static 'assets/js/config.js' %}"></script>
<script src="{% static 'vendors/simplebar/simplebar.min.js' %}"></script>

<!-- ===============================================--><!--    Stylesheets--><!-- ===============================================-->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700%7cPoppins:300,400,500,600,700,800,900&amp;display=swap"
      rel="stylesheet">
<link href="{% static 'vendors/simplebar/simplebar.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/css/theme-rtl.min.css' %}" rel="stylesheet" id="style-rtl">
<link href="{% static 'assets/css/theme.min.css' %}" rel="stylesheet" id="style-default">
<link href="{% static 'assets/css/user-rtl.min.css' %}" rel="stylesheet" id="user-style-rtl">
<link href="{% static 'assets/css/user.min.css' %}" rel="stylesheet" id="user-style-default">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css" />

<style>
    /* For Chrome, Safari, Edge, and Opera */
    input[type="number"]::-webkit-outer-spin-button,
    input[type="number"]::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    /* For Firefox */
    input[type="number"] {
        -moz-appearance: textfield;
    }
</style>
<script>
    var isRTL = JSON.parse(localStorage.getItem('isRTL'));
    if (isRTL) {
        var linkDefault = document.getElementById('style-default');
        var userLinkDefault = document.getElementById('user-style-default');
        linkDefault.setAttribute('disabled', true);
        userLinkDefault.setAttribute('disabled', true);
        document.querySelector('html').setAttribute('dir', 'rtl');
    } else {
        var linkRTL = document.getElementById('style-rtl');
        var userLinkRTL = document.getElementById('user-style-rtl');
        linkRTL.setAttribute('disabled', true);
        userLinkRTL.setAttribute('disabled', true);
    }
</script>

django/templates/parts/scripts.html
{% load static %}

<script src="{% static 'vendors/popper/popper.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'vendors/anchorjs/anchor.min.js' %}"></script>
<script src="{% static 'vendors/is/is.min.js' %}"></script>
<script src="{% static 'vendors/echarts/echarts.min.js' %}"></script>
<script src="{% static 'vendors/fontawesome/all.min.js' %}"></script>
<script src="{% static 'vendors/lodash/lodash.min.js' %}"></script>
{#<script src="{% static 'vendors/list.js/list.min.js' %}"></script>#}
<script src="{% static 'assets/js/theme.js' %}"></script>

django/templates/parts/sidebar.html
{% load static %}
<nav class="navbar navbar-light navbar-vertical navbar-expand-xl navbar-vibrant">
    <div class="d-flex align-items-center">
        <div class="toggle-icon-wrapper">
            <button class="btn navbar-toggler-humburger-icon navbar-vertical-toggle" data-bs-toggle="tooltip"
                    data-bs-placement="left" aria-label="Toggle Navigation"
                    data-bs-original-title="Toggle Navigation">
                <span class="navbar-toggle-icon"><span class="toggle-line"></span></span>
            </button>
        </div>
        <a class="navbar-brand" href="{% url 'web:home' %}">
            <div class="d-flex align-items-center py-3">
                <img class="me-2" src="{% static 'assets/img/icons/spot-illustrations/falcon.png' %}" alt="" width="40">
                <span class="font-sans-serif text-primary">sevinch</span>
            </div>
        </a>
    </div>
    <div class="collapse navbar-collapse" id="navbarVerticalCollapse">
        <div class="navbar-vertical-content scrollbar">
            <ul class="navbar-nav flex-column mb-3" id="navbarVerticalNav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'web:clients:list' %}" role="button">
                        <div class="d-flex align-items-center">
                            <span class="nav-link-icon">
                                <span class="fas fa-user-friends"></span>
                            </span>
                            <span class="nav-link-text ps-1">Shifokor ko'rigi</span>
                        </div>
                    </a>
                    <a class="nav-link" href="{% url 'web:procedures:list' %}" role="button">
                        <div class="d-flex align-items-center">
                            <span class="nav-link-icon">
                                <span class="far fa-file-alt"></span>
                            </span>
                            <span class="nav-link-text ps-1">Registratsiya</span>
                        </div>
                    </a>
                    <a class="nav-link" href="{% url 'web:referrals:list' %}" role="button">
                        <div class="d-flex align-items-center">
                            <span class="nav-link-icon">
                                <span class="fas fa-hospital-user"></span>
                            </span>
                            <span class="nav-link-text ps-1">Hamkor shifokorlar</span>
                        </div>
                    </a>
                    <a class="nav-link" href="{% url 'web:transfers:list' %}" role="button">
                        <div class="d-flex align-items-center">
                            <span class="nav-link-icon">
                                <span class="bi-cash-stack"></span>
                            </span>
                            <span class="nav-link-text ps-1">Kirim chiqimlar</span>
                        </div>
                    </a>
                    <a class="nav-link" href="{% url 'web:statistics:list' %}" role="button">
                        <div class="d-flex align-items-center">
                            <span class="nav-link-icon">
                                <span class="bi-file-bar-graph"></span>
                            </span>
                            <span class="nav-link-text ps-1">Statistika</span>
                        </div>
                    </a>

                </li>
            </ul>
        </div>
    </div>
</nav>